### ISSUE TITLE
using errata-tool also for errata with container content types

### ISSUE THREAD

**Issue by phracek** [red-hat-storage/errata-tool#117]
Hi,

I would like to use your library for file container erratas.
Would it be possible to enhance it with this kind of support.

Based on errata's API https://errata.devel.redhat.com/developer-guide/api-http-api.html#api-advisories
support for container content types shoudl be "tar" (https://errata.devel.redhat.com/developer-guide/api-http-api.html#api-builds)

Greetings
Petr

**Comment by ktdreyer** [comment]
That's right Petr. There's an example in the README, "Adding container builds". We have code like this in OSP and Ceph.

**Comment by phracek** [comment]
Thnx. I did not catch it.
