### ISSUE TITLE
Issue with creating the errata failed with `manager_email` is missing.

### ISSUE THREAD

**Issue by phracek** [red-hat-storage/errata-tool#136]
Hi folks, I have discovered an issue, which seems to be a bug.

I am trying to clone the erratum https://errata.devel.redhat.com/errata/details/37620
and create a new one based on the old one.

Snippet code is:
~~~
    import os
    from time import sleep
    from pprint import pprint
     
    from errata_tool import Erratum, ErrataConnector
     
    ErrataConnector.ssl_verify = False
    ErrataConnector.debug = True
    #ErrataConnector._url = 'https://errata.stage.engineering.redhat.com'
    ErrataConnector._url = 'https://errata.devel.redhat.com'
     
    os.environ['REQUESTS_CA_BUNDLE'] = '/etc/pki/tls/certs/ca-bundle.crt'
    advisory = Erratum(errata_id=37620)
     
    print(advisory.manager_email)
    print(advisory.package_owner_email)
    print(advisory.errata_bugs)

~~~

The manager_email is None.

Do you know, what is the problem about?
Once I want to create a new erratum it fails with the error
~~~
Can't create erratum without manager_email
~~~

I have looked on the code and my code should be ok, 
CC @dhodovsk

This is a bussiness critical. Can you please help me or solve it ASAP.

**Comment by ktdreyer** [comment]
The python-errata-tool test suite contains this test:
```python
    def test_manager_email_is_none(self, advisory):
        # NOTE: the ET does not give this information when querying a
        # pre-existing advisory. We can only update it with POST/PUT, but we
        # cannot GET it.
        #  assert advisory.manager_email == 'gmeno@redhat.com'
        assert advisory.manager_email is None
```
I recommend you file a bug with the Errata Tool team to resolve this server-side.

**Comment by ktdreyer** [comment]
I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1664884 with the Errata Tool team for fixing this in the REST API.

In the mean time, we could expose `.manager_id`, and then you could pass that `int` value into the `User` API like so:

```python
from errata_tool import Erratum
from errata_tool.user import User

advisory = Erratum(errata_id=37620)

maanger_id = advisory.manager_id  # Not implemented yet, but imagine this is an int, 3001353

# This User API already exists, and allows us to identify Stef as the manager:
manager = User(manager_id)
print(manager.email_address)  # swalter@redhat.com
```

**Comment by phracek** [comment]
Yeah, manager_id looks good. It already exists in the Erratum API.
Personally, I don't know when the REST API is gonna be solved and this approach, which you propose,  seems to be better.

**Comment by ktdreyer** [comment]
v1.17.0 has this change
