### ISSUE TITLE
errata_too/erratum.py contain reporter_id

### ISSUE THREAD

**Issue by phracek** [red-hat-storage/errata-tool#141]
I would like to check if an Erratum was reported by some user.

This use case is used by Userspace Containerization team to detect if erratum was created by us or someone else.

**Comment by ktdreyer** [comment]
This should be available in the (oddly named) `Erratum.package_owner_email` attribute

Like in `errata_tool/tests/test_advisory.py`:

    def test_owner_email(self, advisory):
        assert advisory.package_owner_email == 'kdreyer@redhat.com'

**Comment by phracek** [comment]
Ok, will check it.

**Comment by phracek** [comment]
Yeah, this works properly. thanks.

**Comment by ktdreyer** [comment]
Cool. I wonder how we can make this clearer in the documentation.
