### ISSUE TITLE
package_owner_email returns reporter email

### ISSUE THREAD

**Issue by jpopelka** [red-hat-storage/errata-tool#143]
```python
Erratum(errata_id=12345).package_owner_email
```
returns reporter email.

Cause is [here](https://github.com/red-hat-storage/errata-tool/blob/master/errata_tool/erratum.py#L278).

This is actually not just a bug report, but also a feature request, because I need to get the reporter email. I know I can get it with `.package_owner_email`, but that's a bit confusing, you know ;-)

I can work on a patch if you prefere it that way, I just need to know if I can do both in one PR:

- make `.package_owner_email` return package owner
- add `.reporter` which would return reporter

**Comment by ktdreyer** [comment]
Here's a PR to fix this: https://github.com/red-hat-storage/errata-tool/pull/144

**Comment by ktdreyer** [comment]
PR https://github.com/red-hat-storage/errata-tool/pull/144 is in `v1.18.0`. Would you please test this version and let us know if that resolves this issue?

**Comment by jpopelka** [comment]
Works OK for me. Thank you Ken!

**Comment by ktdreyer** [comment]
Thanks!
