### ISSUE TITLE
Adding build failed: Could not find rpms for build

### ISSUE THREAD

**Issue by lioramilbaum** [red-hat-storage/errata-tool#155]
Attaching an image to ET. There should not be rpms in the build.
Attaching manually works fine.

  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/errata_tool/erratum.py", line 693, in addBuilds
    return self.addBuildsDirect(buildlist, release, **kwargs)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/errata_tool/erratum.py", line 672, in addBuildsDirect
    self._processResponse(r)
  File "/home/lmilbaum/.virtualenvs/venv/lib/python2.7/site-packages/errata_tool/connector.py", line 239, in _processResponse
    raise ErrataException(err_msg)
errata_tool.exception.ErrataException: Erratum 40392: Could not find rpms for build cnv-libvirt-cpaas-mvp-container-v1.4.0-2

**Comment by ktdreyer** [comment]
Would you please paste your Python code that calls `addBuilds`?

For containers, you must specify a `file_type` kwarg to let the Errata Tool know what type of build this is. For example:

```python
advisory.addBuilds(['cnv-libvirt-cpaas-mvp-container-v1.4.0-2'],
	       release=product_version,
	       file_types={'cnv-libvirt-cpaas-mvp-container-v1.4.0-2': ['tar']})
```

It would be nice if the ET server's API did not require this.

Is there something we can do in the python-errata-tool docs to make this clearer?

**Comment by lioramilbaum** [comment]
I running it via elliott: https://github.com/openshift/elliott
Let me check how elliott calls the function.

**Comment by lioramilbaum** [comment]
@ktdreyer this was exactly the issue. Thanks for the help.

**Comment by ktdreyer** [comment]
Thanks. How can I help make the documentation clearer about this?

**Comment by lioramilbaum** [comment]
Throw a warning if file_types is not listed in the arguments, or add a warning that the argument will be mandatory in future release.

**Comment by ktdreyer** [comment]
I think we could raise a warning if any build has the string `-container` in the NVR and `file_types` is missing.

I've asked the ET developers about why the server requires `file_types` at all. Maybe a future version of the ET could drop this.

**Comment by lioramilbaum** [comment]
+1
