### ISSUE TITLE
tavis ci is warning about usage of pytest feature that is deprecated

### ISSUE THREAD

**Issue by yazug** [red-hat-storage/errata-tool#163]
=============================== warnings summary ===============================
errata_tool/tests/test_add_builds.py::TestAddBuilds::test_builds_empty_no_release
  /home/travis/build/yazug/errata-tool/errata_tool/tests/test_add_builds.py:35: PytestDeprecationWarning: The 'message' parameter is deprecated.
  (did you mean to use `match='some regex'` to check the exception message?)
  Please comment on https://github.com/pytest-dev/pytest/issues/3974 if you have concerns about removal of this parameter.
    message='Need to specify a release'):
errata_tool/tests/test_add_builds.py::TestAddBuilds::test_builds_new_advisory
  /home/travis/build/yazug/errata-tool/errata_tool/tests/test_add_builds.py:51: PytestDeprecationWarning: The 'message' parameter is deprecated.
  (did you mean to use `match='some regex'` to check the exception message?)
  Please comment on https://github.com/pytest-dev/pytest/issues/3974 if you have concerns about removal of this parameter.
    message='Cannot add builds to unfiled erratum'):
-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by yazug** [comment]
@ktdreyer appears the travisCI is now failing on this.

Job #637.3 on python 3.6 is now failing
https://travis-ci.org/red-hat-storage/errata-tool/jobs/557951272

**Comment by yazug** [comment]
feature was deprecated in pytest 4.1

**Comment by ktdreyer** [comment]
I read that a future version of setuptools is going to deprecate the "test" subcommand entirely. On my other Python projects, I'm switching them all over to `tox` and `tox-travis`. We should do the same for python-errata-tool.

**Comment by ktdreyer** [comment]
I have a work-in-progress branch that switches us over to `tox`. My branch fails without https://github.com/red-hat-storage/errata-tool/pull/165, so I've merged that one now.

**Comment by ktdreyer** [comment]
Here's my change that switches to tox: https://github.com/red-hat-storage/errata-tool/pull/190
