### ISSUE TITLE
ErrataException should provide more information

### ISSUE THREAD

**Issue by shiywang** [red-hat-storage/errata-tool#173]
when Elliott trying to add bugs
```
try
e = Erratum(errata_id=22986)
buglist = [12345, 123678]
e.addBugs(buglist)
e.commit()

except ErrataException as ex
            raise ElliottFatalError(getattr(ex, 'message', repr(ex)))
```

and this is annoying sometimes because it either added it all or added none if there're bugs already attached to some of the other advisories.

So we want to add a retry logic when first time raise ErrataException then find the bug which failed to attach and add it again.
but the information of ErrataException didnt provide much of the information except a string like this
`Erratum 43532: idsfixed: Bug #1487356 The bug is filed already in RHBA-2019:1589.`

So could we add more info into `ErrataException`  like failed bug list ?

**Comment by ktdreyer** [comment]
I see you've already closed this, but I do think it makes sense to open an internal ticket separately with the Errata Tool server team if this is important to you.

Maybe they could return a machine-readable list of problematic BZs in the API response in addition to the human-readable string there.

**Comment by shiywang** [comment]
I did file a issue in [here](https://projects.engineering.redhat.com/browse/ERRATA-8084)
