### ISSUE TITLE
Can we expose the bug query API ?

### ISSUE THREAD

**Issue by shiywang** [red-hat-storage/errata-tool#174]
so we want to using errata-tool to find bugs exist in which advisories. sth similar like in webui https://errata.devel.redhat.com/bugs/1623736/advisories  do this, I believe there is an API for this but I am not sure does errata-tool expose this API ?

**Comment by shiywang** [comment]
@ktdreyer @yazug Do we have that kind of API for errata-tool ?

**Comment by ktdreyer** [comment]
We do not have that now. That would be a great thing to add, perhaps a new `Bug` class.

**Comment by ktdreyer** [comment]
#234 has this now
