### ISSUE TITLE
loading a Build eagerly loads every advisory it was ever attached to

### ISSUE THREAD

**Issue by sosiouxme** [red-hat-storage/errata-tool#179]
Whenever python-errata-tool loads a build, it also loads all associated advisories.
https://github.com/red-hat-storage/errata-tool/blob/035527edb721a761503285ba4333c8f78f801740/errata_tool/build.py#L29-L35

In the case of a build that's been attached to a number of advisories, like https://errata.devel.redhat.com/api/v1/build/thrift-0.9.1-15.el7 -- that can take a while. And it seems really long if you're not interested in the advisories. (In this case we just want to know if it's been signed.)

In the case of an OCP GA advisory with 84 builds (many repeats from previous releases), like e.g. https://errata.devel.redhat.com/advisory/43535 -- it can take a heck of a long time to load all the builds to determine that they've been signed. Loading the same advisories... over and over and over... for no purpose.

Can advisories be loaded lazily for builds?

**Comment by yazug** [comment]
I created at test refactor of build.py to be lazy load
