### ISSUE TITLE
init kerb auth with mutual_authentication=DISABLED

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/errata-tool#18]
We should be able to eliminate this try-catch exception for `requests_kerberos.exceptions.MutualAuthenticationError`:

```
# Handle weird interaction we get in this particular case
try:
    r = self._post(url, data=pdata)
except requests_kerberos.exceptions.MutualAuthenticationError:
    pass
```

we can just initialize `HTTPKerberosAuth(mutual_authentication=DISABLED)`.

**Comment by yazug** [comment]
I have a test patch and it seems to work, should we make it configurable or always on?

**Comment by ktdreyer** [comment]
Apparently this reflects an underlying problem in the ET's web server infrastructure (see tech-list thread with Simo). We should develop a minimal reproducer where the Mutual Auth failure happens and open a ticket with the ET team.

**Comment by lhh** [comment]
Actually, other related APIs need this disabled - for now, it's best to turn it off.

**Comment by lhh** [comment]
(Such as request-sigs)

**Comment by ktdreyer** [comment]
@lhh, mind sending me your reproduction case for when request-sigs fails? we can minimize the reproducer and then I can raise this with the ET team and the Kerberos team
