### ISSUE TITLE
Add bugs using CLI

### ISSUE THREAD

**Issue by rh-hectormartinezdev** [red-hat-storage/errata-tool#240]
Hello!

I want to be able to add bugs from the command line. My proposal is basically mimicking what is already there:

```
errata-tool advisory add-bugs <advisory-id> --bugs-ids <bug-id> <bug-id>
```

I already have a branch with the implementation, if this is interesting, I can open an MR.

**Comment by ktdreyer** [comment]
It's a great idea. Please do open a PR.

**Comment by hemartin-at-redhat** [comment]
I submitted https://github.com/red-hat-storage/errata-tool/pull/241
